### ISSUE TITLE
Many errors while building

### ISSUE THREAD

**Issue by RealKalsep** [Klaykap/BleskOS#2]
When I try to run compile.sh in nasm:
```
compile.sh:1: error: label or instruction expected at start of line
compile.sh:3: error: parser: instruction expected
compile.sh:5: error: parser: instruction expected
compile.sh:6: error: parser: instruction expected
compile.sh:8: error: expression syntax error
compile.sh:9: error: comma expected after operand
compile.sh:10: error: comma expected after operand
compile.sh:12: error: parser: instruction expected
compile.sh:14: error: parser: instruction expected
```

When I try to do commands manually, this one errors first (nasm -f bin source/bleskos.asm -o images/bleskos.bin)
and I cannot continue:
```
source/drivers/sound_center.asm:39: error: parser: instruction expected
source/bleskos.asm:46: error: label `IF_NE' inconsistently redefined
source/drivers/sound_center.asm:39: info: label `IF_NE' originally defined here
source/bleskos.asm:46: error: parser: instruction expected
source/bleskos.asm:48: error: label `IF_NE.if_ac97' inconsistently redefined
source/bleskos.asm:138: ... from macro `ENDIF' defined here
source/bleskos.asm:48: info: label `IF_NE.if_ac97' originally defined here
source/bleskos.asm:53: error: label `IF_NE' inconsistently redefined
source/bleskos.asm:46: info: label `IF_NE' originally defined here
source/bleskos.asm:53: error: parser: instruction expected
source/bleskos.asm:55: error: label `IF_NE.if_ac97' inconsistently redefined
source/bleskos.asm:138: ... from macro `ENDIF' defined here
source/bleskos.asm:55: info: label `IF_NE.if_ac97' originally defined here
source/bleskos.asm:60: error: label `IF_NE' inconsistently redefined
source/bleskos.asm:53: info: label `IF_NE' originally defined here
source/bleskos.asm:60: error: parser: instruction expected
source/bleskos.asm:63: error: label `IF_NE.if_ac97' inconsistently redefined
source/bleskos.asm:138: ... from macro `ENDIF' defined here
source/bleskos.asm:63: info: label `IF_NE.if_ac97' originally defined here
source/bleskos.asm:68: error: label `IF_NE' inconsistently redefined
source/bleskos.asm:60: info: label `IF_NE' originally defined here
source/bleskos.asm:68: error: parser: instruction expected
source/bleskos.asm:70: error: label `IF_NE.if_ac97' inconsistently redefined
source/bleskos.asm:138: ... from macro `ENDIF' defined here
source/bleskos.asm:70: info: label `IF_NE.if_ac97' originally defined here
source/drivers/hardware_ps2_keyboard.asm:46: warning: unterminated string [-w+ot
her]

```

All code is from this github

**Comment by Klaykap** [comment]
Thank for feedback! I forgot update one file, from it comes error messages. I fixed it now. For compile, compile.sh is file for compiling BleskOS in linux distributions. You can not run it from nasm. When you download code, open Properties of compile.sh and check Run this file as program. After this you can double click on it and it will compile.

**Comment by RealKalsep** [comment]
What program can I use?

**Comment by Klaykap** [comment]
If you are in linux you do not need any program, .sh is file whose contains commands for command line. Check Run this file as program is need for tell linux you want to run commands from this file, not open this file in text editor.

**Comment by RealKalsep** [comment]
I was in windows

**Comment by Klaykap** [comment]
Oh, I have tried to make compile file for Windows but it was not successful. Theoretically you can follow these steps:

1. Download code, extract it and open folder BleskOS-master
2. Create folder “images”
3. Compile file bootloader.asm in folder “bootloader” to file bootloader.bin
4. Compile file bleskos.asm in folder “source” to file bleskos.bin and put it into folder “images”
5. Create free file bleskos.hdd to folder “images” with enough size (1 MB is good)
6. Raw write file bootloader.bin to start of file bleskos.hdd
7. Raw write file bleskos.bin to file bleskos.hdd from byte 512 - in other words, after bootloader.bin
8. Attach bleskos.hdd to Virtualbox as hard disk or to QEMU and run it

These steps are followed in file compile.sh. NASM commands are probably too same, but I do not found usable replace of program dd.

**Comment by RealKalsep** [comment]
Thank you, it now works. I used DD for Windows (http://www.chrysocome.net/dd), compiled it as normal, ran it in VirtualBox. But there's a bit of a problem with the graphics. https://i.imgur.com/57VSmfB.png

**Comment by RealKalsep** [comment]
It now works, thanks
