### ISSUE TITLE
Graphics warping

### ISSUE THREAD

**Issue by RealKalsep** [Klaykap/BleskOS#3]
When I run the system in VirtualBox, the "main menu" is warped to the left. Screenshot: https://i.imgur.com/57VSmfB.png

**Comment by Klaykap** [comment]
Please can you open developer zone and hardware info and post screen here? I have some ideas what can cause that but it will be easier for me with this informations.

**Comment by RealKalsep** [comment]
Sure, also keep in mind it's on VirtualBox: 
![image](https://user-images.githubusercontent.com/61381739/106503906-87d33480-64c6-11eb-9c49-b96e794aaa8c.png)

**Comment by Klaykap** [comment]
Thank you, I fixed this problem. Code on github is updated.
